### ISSUE TITLE
Redicionamento de domínios

### ISSUE THREAD

**Issue by lpirola** [ForaDoEixo/MidiaNinja.org#12]
Ordem de prioridade de redirecionamento

midianinja.org
midianinja.org.br
midianinja.com.br
midia.ninja

**Comment by jacsonp** [comment]
Precisa do acesso ao domínios, e redirecionar para redelivre.org.br (177.71.196.145)

**Comment by jacsonp** [comment]
midianinja.org.br
midianinja.com.br
Colocar japas16 como id técnico

**Comment by BrancaSchulz** [comment]
foi feito! =)

**Comment by BrancaSchulz** [comment]
Falta apenas o redirecionamento do midia.ninja pelo Hacklab

**Comment by jacsonp** [comment]
Feito
